# Generated by Django 5.0.5 on 2024-08-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_favorite_author_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='article',
            new_name='product',
        ),
    ]
